package com.kingfisher.payment.api.optile.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.constraints.NotNull;
import java.util.Objects;

/**
 * ReturnCode
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2017-12-13T09:50:13.086Z")

public class ReturnCode   {
  @JsonProperty("name")
  private String name = null;

  @JsonProperty("source")
  private String source = null;

  public ReturnCode name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Unified return code name to indicate success or reason for an error; the code is unified across OPG platform, it is independent from underlying PSP or institution service; e.g. \"OK\", \"NON_SUFFICIENT_FUNDS\", \"INVALID_ACCOUNT_NUMBER\", etc. 
   * @return name
  **/
  @ApiModelProperty(example = "NON_SUFFICIENT_FUNDS", required = true, value = "Unified return code name to indicate success or reason for an error; the code is unified across OPG platform, it is independent from underlying PSP or institution service; e.g. \"OK\", \"NON_SUFFICIENT_FUNDS\", \"INVALID_ACCOUNT_NUMBER\", etc. ")
  @NotNull


  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ReturnCode source(String source) {
    this.source = source;
    return this;
  }

   /**
   * System that generated this return code; currently supported values: \"GATEWAY\" - indicates that return code is generated by OPG platform, \"PSP\" - if return code is a result of mapping from payment service provider code, and \"INSTITUTION\" - for those codes that wer originally generated by financial institution (issuing or acquiring banks) 
   * @return source
  **/
  @ApiModelProperty(example = "INSTITUTION", required = true, value = "System that generated this return code; currently supported values: \"GATEWAY\" - indicates that return code is generated by OPG platform, \"PSP\" - if return code is a result of mapping from payment service provider code, and \"INSTITUTION\" - for those codes that wer originally generated by financial institution (issuing or acquiring banks) ")
  @NotNull


  public String getSource() {
    return source;
  }

  public void setSource(String source) {
    this.source = source;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnCode returnCode = (ReturnCode) o;
    return Objects.equals(this.name, returnCode.name) &&
        Objects.equals(this.source, returnCode.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, source);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnCode {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

